<?php
/**
 * Front page.
 *
 * @package MaxPost
 */

get_header();
$featured    = function_exists( 'maxpost_get_featured_software' ) ? maxpost_get_featured_software( 3 ) : [];
$archive_url = get_post_type_archive_link( 'software' ) ?: home_url( '/software/' );
$latest      = new WP_Query( [ 'post_type' => 'software', 'post_status' => 'publish', 'posts_per_page' => 6, 'no_found_rows' => true, 'orderby' => 'modified', 'order' => 'DESC' ] );
$latest_update = $latest->posts[0] ?? null;
?>
<main id="main">
	<section class="hero hero--product"><div class="hero__glow hero__glow--one"></div><div class="hero__glow hero__glow--two"></div><div class="mp-container hero__grid">
		<div class="hero__content"><p class="eyebrow"><span></span><?php esc_html_e( 'Independent Windows software', 'maxpost' ); ?></p><h1><?php esc_html_e( 'Small tools.', 'maxpost' ); ?><br><em><?php esc_html_e( 'Serious time savings.', 'maxpost' ); ?></em></h1><p class="hero__lead"><?php esc_html_e( 'Focused utilities for files, folders, images and everyday Windows tasks. No accounts, no bundles and no unnecessary complexity.', 'maxpost' ); ?></p><div class="hero__actions"><a class="mp-button mp-button--primary" href="<?php echo esc_url( $archive_url ); ?>"><?php esc_html_e( 'Explore software', 'maxpost' ); ?><span>→</span></a><a class="mp-button mp-button--secondary" href="#whats-new"><?php esc_html_e( 'See what’s new', 'maxpost' ); ?></a></div><div class="trust-row"><span><b>✓</b><?php esc_html_e( 'Free to use', 'maxpost' ); ?></span><span><b>✓</b><?php esc_html_e( 'Windows 10/11', 'maxpost' ); ?></span><span><b>✓</b><?php esc_html_e( '5 languages', 'maxpost' ); ?></span></div></div>
		<div class="hero-suite"><div class="suite-window"><div class="suite-window__title"><div><span>MP</span><strong>Folder Creator</strong></div><small>— □ ×</small></div><div class="suite-window__body"><div class="suite-workspace"><p>1. Select location</p><div class="suite-input"></div><p>2. Folder names</p><div class="suite-list"><i></i><i></i><i></i><i></i></div><div class="suite-options"><span>☑ Use numbers</span><span>☑ Create if missing</span></div><button type="button" tabindex="-1">Create folders</button></div><aside class="suite-sidebar"><strong><?php esc_html_e( 'Try more tools', 'maxpost' ); ?></strong><ul><li><span>R</span>Bulk Rename</li><li><span>I</span>Image Converter</li><li><span>D</span>Duplicate Finder</li></ul><div class="suite-news"><small><?php esc_html_e( 'What’s new', 'maxpost' ); ?></small><b>Image Converter 2.0</b><a href="#whats-new"><?php esc_html_e( 'View update', 'maxpost' ); ?> →</a></div><div class="suite-support"><small><?php esc_html_e( 'Support MaxPost', 'maxpost' ); ?></small><b><?php esc_html_e( 'Help independent software grow.', 'maxpost' ); ?></b></div></aside></div><div class="suite-status"><span>✓ <?php esc_html_e( '250 folders created successfully', 'maxpost' ); ?></span><span><?php esc_html_e( 'Open folder', 'maxpost' ); ?></span></div></div></div>
	</div></section>
	<section class="proof-strip"><div class="mp-container proof-strip__inner"><p><?php esc_html_e( 'Built around one rule:', 'maxpost' ); ?></p><strong><?php esc_html_e( 'One tool. One task. Done.', 'maxpost' ); ?></strong><div class="proof-metrics"><span><b>6</b><?php esc_html_e( 'utilities', 'maxpost' ); ?></span><span><b>5</b><?php esc_html_e( 'languages', 'maxpost' ); ?></span><span><b>0</b><?php esc_html_e( 'accounts', 'maxpost' ); ?></span></div></div></section>
	<section class="section why-section"><div class="mp-container"><div class="section-heading section-heading--split"><div><p class="eyebrow"><span></span><?php esc_html_e( 'Why MaxPost', 'maxpost' ); ?></p><h2><?php esc_html_e( 'Software that stays out of your way.', 'maxpost' ); ?></h2></div><p><?php esc_html_e( 'Every utility is built around one clear job, with native-feeling Windows interfaces and no hidden ecosystem lock-in.', 'maxpost' ); ?></p></div><div class="principles-grid"><article class="feature-principle"><span>01</span><h3><?php esc_html_e( 'Focused by design', 'maxpost' ); ?></h3><p><?php esc_html_e( 'No feature maze. Each application solves a specific problem well.', 'maxpost' ); ?></p></article><article class="feature-principle"><span>02</span><h3><?php esc_html_e( 'Private by default', 'maxpost' ); ?></h3><p><?php esc_html_e( 'Your files stay on your computer. Accounts are not required.', 'maxpost' ); ?></p></article><article class="feature-principle"><span>03</span><h3><?php esc_html_e( 'Small and fast', 'maxpost' ); ?></h3><p><?php esc_html_e( 'Compact downloads, low memory use and predictable behavior.', 'maxpost' ); ?></p></article></div></div></section>
	<section id="featured" class="section section--surface"><div class="mp-container"><div class="section-heading section-heading--split"><div><p class="eyebrow"><span></span><?php esc_html_e( 'Featured software', 'maxpost' ); ?></p><h2><?php esc_html_e( 'Useful from the first click.', 'maxpost' ); ?></h2></div><a class="text-link" href="<?php echo esc_url( $archive_url ); ?>"><?php esc_html_e( 'View all software', 'maxpost' ); ?> →</a></div><?php if ( $featured ) : ?><div class="software-grid"><?php foreach ( $featured as $item ) : $GLOBALS['post'] = get_post( $item['id'] ); setup_postdata( $GLOBALS['post'] ); get_template_part( 'template-parts/software-card' ); endforeach; wp_reset_postdata(); ?></div><?php else : ?><div class="empty-state"><strong><?php esc_html_e( 'Featured software is ready for content.', 'maxpost' ); ?></strong></div><?php endif; ?></div></section>
	<section id="whats-new" class="section"><div class="mp-container"><div class="updates-layout"><article class="update-feature whats-new-panel"><p class="eyebrow"><span></span><?php esc_html_e( 'What’s new', 'maxpost' ); ?></p><?php if ( $latest_update ) : ?><h2><?php echo esc_html( get_the_title( $latest_update ) ); ?> <em><?php esc_html_e( 'updated', 'maxpost' ); ?></em></h2><p><?php echo esc_html( get_the_excerpt( $latest_update ) ); ?></p><ul><li><?php esc_html_e( 'Modernized interface and clearer workflow', 'maxpost' ); ?></li><li><?php esc_html_e( 'Improved performance and stability', 'maxpost' ); ?></li><li><?php esc_html_e( 'Better multilingual support', 'maxpost' ); ?></li></ul><a class="mp-button mp-button--secondary" href="<?php echo esc_url( get_permalink( $latest_update ) ); ?>"><?php esc_html_e( 'View details', 'maxpost' ); ?></a><?php else : ?><h2><?php esc_html_e( 'Product updates will appear here.', 'maxpost' ); ?></h2><?php endif; ?></article><aside class="support-panel"><span>♥</span><h3><?php esc_html_e( 'Support independent software', 'maxpost' ); ?></h3><p><?php esc_html_e( 'MaxPost is built independently. Support helps fund development, testing and translations.', 'maxpost' ); ?></p><a class="mp-button mp-button--primary" href="<?php echo esc_url( home_url( '/support/' ) ); ?>"><?php esc_html_e( 'Support MaxPost', 'maxpost' ); ?></a></aside></div></div></section>
	<section class="section section--surface"><div class="mp-container"><div class="section-heading"><p class="eyebrow"><span></span><?php esc_html_e( 'Browse by task', 'maxpost' ); ?></p><h2><?php esc_html_e( 'Start with what you need to do.', 'maxpost' ); ?></h2></div><div class="category-grid"><?php foreach ( [ [ 'Files & folders', 'Create, rename and organize faster.', '⌘' ], [ 'Images', 'Convert and prepare visual assets.', '◫' ], [ 'Archives', 'Work with compressed files safely.', '▣' ], [ 'Text', 'Clean, transform and automate text.', 'T' ], [ 'System', 'Small tools for everyday Windows tasks.', '⚙' ], [ 'Developer', 'Focused helpers for technical work.', '</>' ] ] as $category ) : ?><a class="category-card" href="<?php echo esc_url( $archive_url ); ?>"><span><?php echo esc_html( $category[2] ); ?></span><div><h3><?php echo esc_html( $category[0] ); ?></h3><p><?php echo esc_html( $category[1] ); ?></p></div><b>↗</b></a><?php endforeach; ?></div></div></section>
	<section class="section"><div class="mp-container"><div class="section-heading section-heading--split"><div><p class="eyebrow"><span></span><?php esc_html_e( 'All software', 'maxpost' ); ?></p><h2><?php esc_html_e( 'The MaxPost toolbox.', 'maxpost' ); ?></h2></div><a class="text-link" href="<?php echo esc_url( $archive_url ); ?>"><?php esc_html_e( 'View complete catalog', 'maxpost' ); ?> →</a></div><?php get_template_part( 'template-parts/software-table' ); ?></div></section>
	<section class="section section--cta"><div class="mp-container"><div class="cta-panel"><div><p class="eyebrow"><span></span><?php esc_html_e( 'Built independently', 'maxpost' ); ?></p><h2><?php esc_html_e( 'Software should solve problems, not create new ones.', 'maxpost' ); ?></h2></div><a class="mp-button mp-button--primary" href="<?php echo esc_url( $archive_url ); ?>"><?php esc_html_e( 'Browse MaxPost tools', 'maxpost' ); ?> →</a></div></div></section>
</main>
<?php get_footer(); ?>
